### ISSUE TITLE
Idea for a new mod

### ISSUE THREAD

**Issue by Frisk197** [Lauriethefish/Quest-Discord-Presence-Client#1]
Hey could you do the same thing as the discord presence but with twitch please ?
That would be really helpfull for me and others tryng to start live stream from the quest.

**Comment by Lauriethefish** [comment]
Beyond the scope of this mod, this isn't the right place to make a request like this.

Try BSMG's ``#mod-requests``, but this is unlikely to get you anywhere.
You could always try commissioning someone to do it on the commissions server.

Although, if I recall correctly, somebody is already working on this.
