### ISSUE TITLE
Update to 1.21.0

### ISSUE THREAD

**Issue by auggeeo** [Lauriethefish/Quest-Discord-Presence-Client#12]
Hi @Lauriethefish! (I'm very very sorry if you got a lot of these annoying messages already. Also I am not trying to do spam at all I was just trying to ask.)
I just wanted to ask if you can update Breaktime to 1.21.0?

Thanks,
@CoopPlayzz

**Comment by Lauriethefish** [comment]
No? That's not my mod

**Comment by auggeeo** [comment]
Oh i just noticed, sorry! i did not know.
