### ISSUE TITLE
Add option to disable app window opening on startup

### ISSUE THREAD

**Issue by M-Ryba** [Lauriethefish/Quest-Discord-Presence-Client#2]
Add an option to disable starting in window on startup even when the quest 2 is not reachable. I don't like having to close it every time I power on my computer.

**Comment by Lauriethefish** [comment]
I can probably add a command line option that does this, then you can just modify the shortcut to pass that command line option.

**Comment by M-Ryba** [comment]
That would be cool

**Comment by Lauriethefish** [comment]
I'll add it later today. Could I have your discord tag to talk it over?

**Comment by M-Ryba** [comment]
> I'll add it later today. Could I have your discord tag to talk it over?

MRyba #1929
