### ISSUE TITLE
Unable to launch

### ISSUE THREAD

**Issue by BhOmers** [Lauriethefish/Quest-Discord-Presence-Client#4]
Good afternoon, I’m on Mac and followed the instructions to open Quest-Discord-Prescence-Client but it just opens as it text file. I have followed everything correctly up to this point.

**Comment by PCdaBEST** [comment]
I had the same problem. Just a bunch of random text and symbols

**Comment by Lauriethefish** [comment]
Caused by the cross-platform UI framework I'm doing not properly starting on MacOS for unknown reasons.
For now, use [madmagic's client](https://github.com/madmagic007/Oculus-Quest-Presence) instead.
