### ISSUE TITLE
cant launch, windows thinks its a virus

### ISSUE THREAD

**Issue by TatttletailHGL** [Lauriethefish/Quest-Discord-Presence-Client#5]
"Microsoft Defender SmartScreen prevented an unrecognized app from starting. Running this app might put your PC at risk.
App: | windows-installer.exe
Publisher: | Unknown publisher"

any help?

**Comment by Lauriethefish** [comment]
Press more info and then run anyway.

**Comment by TatttletailHGL** [comment]
i dont see a run anyway
![help2](https://user-images.githubusercontent.com/72512818/110665873-c9768f80-8196-11eb-88dd-cc9780f7d65f.PNG)

**Comment by TatttletailHGL** [comment]
> Press more info and then run anyway.

i dont see a run anyway
![help2](https://user-images.githubusercontent.com/72512818/110673622-021a6700-819f-11eb-9322-f2fa3d9b3f50.PNG)
